FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git=1:2.34.1-1ubuntu1.10 \
    python3=3.10.6-1~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.4

RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR /devops-examples/EXAMPLE_APP/

ADD requirements.txt .
RUN pip install -r requirements.txt

ADD add_host.patch .
RUN patch main.py add_host.patch

ENTRYPOINT ["python3", "main.py"]
